# Generated by Django 3.0.2 on 2020-02-11 02:18

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    def default_time():
        return timezone.now() + timezone.timedelta(+14)

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('published_at', models.DateTimeField(default=default_time)),
                ('created_at', models.DateTimeField(default=default_time)),
                ('updated_at', models.DateTimeField(default=default_time))
            ],
        ),
    ]
